import { agentById } from '../agents'
import type { ArtifactReceipt, UiManifest, UseCaseDefinition } from '../types'

type ReceiptDissolveProps = {
  artifactReceipt?: ArtifactReceipt
  useCase: UseCaseDefinition
  manifest: UiManifest
  onDismiss: () => void
}

export function ReceiptDissolve({ artifactReceipt, useCase, manifest, onDismiss }: ReceiptDissolveProps) {
  const argumentCount = manifest.argument.length
  const lensObjections = manifest.argument.filter((line) => line.agent === 'lens').length
  const lastSpeaker = manifest.argument[manifest.argument.length - 1]?.agent ?? 'wild'
  const lastSpeakerName = agentById(lastSpeaker).name
  const tagline = manifest.receiptTagline

  return (
    <section className="receipt-shell" role="dialog" aria-label="Execution receipt">
      <div className="receipt-card">
        <div className="receipt-banner">
          <span className="receipt-orb" />
          <p className="eyebrow">The surface dissolved on purpose</p>
        </div>
        <h2>{artifactReceipt ? 'A real output packet was created.' : 'The local export is still resolving.'}</h2>
        <p>
          AgenticPrime completed the <strong>{useCase.title}</strong> run and wrote the approved surface into local
          files you can inspect, edit, submit, or hand to another agent.
        </p>

        <div className="receipt-fingerprint" aria-label="Argument fingerprint">
          {manifest.closingLines.map((line) => {
            const agent = agentById(line.agent)
            return (
              <div
                key={`${line.agent}-${line.text}`}
                className={`receipt-line author-${line.agent}`}
                style={{ '--author-color': agent.color, '--author-glow': agent.glow } as React.CSSProperties}
              >
                <span className="author-dot" />
                <strong>{agent.name}:</strong>
                <span>{line.text}</span>
              </div>
            )
          })}
        </div>

        <p className="receipt-tagline">&ldquo;{tagline}&rdquo;</p>

        <div className="receipt-stats">
          <div>
            <span className="receipt-stat-label">Lines exchanged</span>
            <strong>{argumentCount}</strong>
          </div>
          <div>
            <span className="receipt-stat-label">Times Lens objected</span>
            <strong>{lensObjections}</strong>
          </div>
          <div>
            <span className="receipt-stat-label">Last word</span>
            <strong>{lastSpeakerName}</strong>
          </div>
        </div>

        {artifactReceipt ? (
          <>
            <div className="artifact-folder">
              <span>Output folder</span>
              <code>{artifactReceipt.folder}</code>
            </div>
            <ul className="artifact-list">
              {artifactReceipt.files.map((file) => (
                <li key={file.path}>
                  <strong>{file.label}</strong>
                  <code>{file.path}</code>
                  <span>{file.purpose}</span>
                </li>
              ))}
            </ul>
          </>
        ) : (
          <ul className="action-list">
            {useCase.approval.actions.map((action) => (
              <li key={action}>Approved: {action}</li>
            ))}
          </ul>
        )}

        <p className="receipt-fineprint">
          {artifactReceipt?.summary ??
            'If export fails, the app will show the failure here instead of pretending work happened.'}
        </p>
        <p className="receipt-cheeky">
          Generated by five arguing dinosaurs. Disagreement is the architecture.
        </p>
        <div className="intent-actions">
          <button className="secondary-action" type="button" onClick={onDismiss}>
            Start another surface
          </button>
        </div>
      </div>
    </section>
  )
}

type DissolveCurtainProps = {
  manifest: UiManifest
}

export function DissolveCurtain({ manifest }: DissolveCurtainProps) {
  const lines = manifest.closingLines
  return (
    <div className="dissolve-curtain" role="presentation" aria-hidden="true">
      <div className="dissolve-veil" />
      <div className="dissolve-particles">
        {Array.from({ length: 16 }).map((_, index) => (
          <span key={index} className={`dissolve-spark spark-${index % 5}`} />
        ))}
      </div>
      <div className="dissolve-lines">
        {lines.map((line, index) => {
          const agent = agentById(line.agent)
          return (
            <div
              key={`${line.agent}-${index}`}
              className={`dissolve-line author-${line.agent}`}
              style={{
                '--author-color': agent.color,
                '--author-glow': agent.glow,
                animationDelay: `${index * 240}ms`,
              } as React.CSSProperties}
            >
              <span className="author-dot" />
              <strong>{agent.name}</strong>
              <span>{line.text}</span>
            </div>
          )
        })}
      </div>
    </div>
  )
}
